### ISSUE TITLE
Fedora is missing ceres-solver

### ISSUE THREAD

**Issue by cottsay** [smd-ros-rpm-release/triage#12]
Tracking as [RHBZ#1183193](https://bugzilla.redhat.com/show_bug.cgi?id=1183193)

**Comment by richmattes** [comment]
bug report closed, submitted to rosdistro at https://github.com/ros/rosdistro/pull/8527

**Comment by richmattes** [comment]
Pull request merged - we're all set.

**Comment by cottsay** [comment]
Thanks, Rich!
