### ISSUE TITLE
FTBFS: pcl_ros (22+)

### ISSUE THREAD

**Issue by cottsay** [smd-ros-rpm-release/triage#15]
Example failure: https://csc.mcs.sdsmt.edu/jenkins/job/ros-jade-pcl-ros_binaryrpm_22_x86_64/4/console

f22 is in Alpha right now, so this might be a Fedora bug.

**Comment by richmattes** [comment]
Relevant error:
make[2]: **\* No rule to make target '/usr/lib64/libnetcdf_c++.so', needed by 'devel/lib/libpcl_ros_surface.so'.  Stop.

It appears we may need to bring in libnetcdf-c++-devel in with pcl-devel

**Comment by richmattes** [comment]
Tracking this as [RHBZ#1224512](https://bugzilla.redhat.com/show_bug.cgi?id=1224512)

**Comment by cottsay** [comment]
Looks like this has been pushed. I'll leave this open until we verify the fix.

**Comment by richmattes** [comment]
There haven't been any build attempts since March 25 - any way to force a rebuild?

https://csc.mcs.sdsmt.edu/jenkins/job/ros-jade-pcl-ros_binaryrpm_22_x86_64/

**Comment by cottsay** [comment]
Confirmed fixed. Closing.
